### ISSUE TITLE
There is NaN appearing in obs.

### ISSUE THREAD

**Issue by Fxy000** [Alescontrela/AMP_for_hardware#29]
Hello everyone, I encountered the following error every time I tried to use a humanoid robot in this framework:
Traceback (most recent call last):
  File "legged_gym/scripts/train.py", line 47, in <module>
    train(args)
  File "legged_gym/scripts/train.py", line 43, in train
    ppo_runner.learn(num_learning_iterations=train_cfg.runner.max_iterations, init_at_random_ep_len=True)
  File "/home/xinyu/AMP_for_WK4_new/rsl_rl/rsl_rl/runners/amp_on_policy_runner.py", line 135, in learn
    actions = self.alg.act(obs, critic_obs, amp_obs)
  File "/home/xinyu/AMP_for_WK4_new/rsl_rl/rsl_rl/algorithms/amp_ppo.py", line 120, in act
    self.transition.actions = self.actor_critic.act(aug_obs).detach()
  File "/home/xinyu/AMP_for_WK4_new/rsl_rl/rsl_rl/modules/actor_critic.py", line 128, in act
    self.update_distribution(observations)
  File "/home/xinyu/AMP_for_WK4_new/rsl_rl/rsl_rl/modules/actor_critic.py", line 125, in update_distribution
    self.distribution = Normal(mean, mean*0. + std)
  File "/home/xinyu/miniconda3/envs/amp_for_wk4/lib/python3.8/site-packages/torch/distributions/normal.py", line 50, in __init__
    super(Normal, self).__init__(batch_shape, validate_args=validate_args)
  File "/home/xinyu/miniconda3/envs/amp_for_wk4/lib/python3.8/site-packages/torch/distributions/distribution.py", line 55, in __init__
    raise ValueError(
ValueError: Expected parameter loc (Tensor of shape (10, 21)) of distribution Normal(loc: torch.Size([10, 21]), scale: torch.Size([10, 21])) to satisfy the constraint Real(), but found invalid values:
I tried modifying the added_mass_range, but it didn't work.
Additionally, when I used test_env.py for testing, I found that the robot was flying around uncontrollably in Isaac Gym.

https://github.com/user-attachments/assets/6fa84ffd-f6d4-4224-b94c-3595a5e304d8

**Comment by pullitdown** [comment]
hi, bro! i meet same problem,have any way to solve it?
