### ISSUE TITLE
RuntimeError: vstack expects a non-empty TensorList

### ISSUE THREAD

**Issue by thisisnotahuman** [Alescontrela/AMP_for_hardware#9]
i just followed readme.md 
when running train.py or play.py:

Traceback (most recent call last):
  File "../AMP_for_hardware-main/legged_gym/scripts/play.py", line 126, in <module>
    play(args)
  File "../AMP_for_hardware-main/legged_gym/scripts/play.py", line 58, in play
    env, _ = task_registry.make_env(name=args.task, args=args, env_cfg=env_cfg)
  File "../AMP_for_hardware-main/legged_gym/utils/task_registry.py", line 97, in make_env
    env = task_class(   cfg=env_cfg,
  File "../AMP_for_hardware-main/legged_gym/envs/base/legged_robot.py", line 90, in __init__
    self.amp_loader = AMPLoader(motion_files=self.cfg.env.amp_motion_files, device=self.device, time_between_frames=self.dt)
  File "../AMP_for_hardware-main/rsl_rl/rsl_rl/datasets/motion_loader.py", line 131, in __init__
    self.all_trajectories_full = torch.vstack(self.trajectories_full)
RuntimeError: vstack expects a non-empty TensorList

**Comment by thisisnotahuman** [comment]
issue Apr 15 2022
